#博客名称
title: 
#副标题
subtitle: 吾生有崖而知无涯 /托腮！
#简介
description: QQ：260647115<br/>微信：yxs260647115<br/>同城交友：https://github.com/yuanxiaosi
#博客作者
author: yuanxiaosi
#博客语言
language: zh-Hans
#时区
timezone:

#博客地址,与申请的GitHub一致
url: http://vicky.github.io
root: /blog/
#博客链接格式
permalink: :year/:month/:day/:title/
permalink_defaults:

source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

default_category: uncategorized
category_map:
tag_map:

#日期格式
date_format: YYYY-MM-DD
time_format: HH:mm:ss

#分页，每页文章数量
per_page: 10
pagination_dir: page

#博客主题
theme: next-theme

#发布设置
deploy: 
  type: git
  #elfwalk改为你的github用户名
  repository: https://github.com/yuanxiaosi/blog.git
  branch: master